# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sync_pb2 as sync__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyncServiceStub:
    """─── Service ──────────────────────────────────────────────────────────────────

    Bookmarks are included in regular file sync as .obsidian/bookmarks.json.
    No separate RPC is needed for them.

    For gRPC-Web compatibility, bidirectional streaming was dropped in favor of batch-request-based
    server streaming.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/obsidian.sync.v1.SyncService/Ping',
                request_serializer=sync__pb2.Empty.SerializeToString,
                response_deserializer=sync__pb2.Pong.FromString,
                _registered_method=True)
        self.Delta = channel.unary_unary(
                '/obsidian.sync.v1.SyncService/Delta',
                request_serializer=sync__pb2.DeltaRequest.SerializeToString,
                response_deserializer=sync__pb2.DeltaResponse.FromString,
                _registered_method=True)
        self.UploadFiles = channel.unary_stream(
                '/obsidian.sync.v1.SyncService/UploadFiles',
                request_serializer=sync__pb2.UploadBatch.SerializeToString,
                response_deserializer=sync__pb2.UploadAck.FromString,
                _registered_method=True)
        self.DownloadFiles = channel.unary_stream(
                '/obsidian.sync.v1.SyncService/DownloadFiles',
                request_serializer=sync__pb2.DownloadBatchRequest.SerializeToString,
                response_deserializer=sync__pb2.FileChunk.FromString,
                _registered_method=True)
        self.GetFileHistory = channel.unary_unary(
                '/obsidian.sync.v1.SyncService/GetFileHistory',
                request_serializer=sync__pb2.HistoryRequest.SerializeToString,
                response_deserializer=sync__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.DownloadHistoryVersion = channel.unary_stream(
                '/obsidian.sync.v1.SyncService/DownloadHistoryVersion',
                request_serializer=sync__pb2.HistoryVersionDownloadRequest.SerializeToString,
                response_deserializer=sync__pb2.FileChunk.FromString,
                _registered_method=True)
        self.RestoreHistoryVersion = channel.unary_unary(
                '/obsidian.sync.v1.SyncService/RestoreHistoryVersion',
                request_serializer=sync__pb2.RestoreHistoryRequest.SerializeToString,
                response_deserializer=sync__pb2.RestoreHistoryResponse.FromString,
                _registered_method=True)


class SyncServiceServicer:
    """─── Service ──────────────────────────────────────────────────────────────────

    Bookmarks are included in regular file sync as .obsidian/bookmarks.json.
    No separate RPC is needed for them.

    For gRPC-Web compatibility, bidirectional streaming was dropped in favor of batch-request-based
    server streaming.

    """

    def Ping(self, request, context):
        """Check the connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delta(self, request, context):
        """Step 1: compare metadata → determine the upload/download lists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFiles(self, request, context):
        """Step 2-A: upload N files (single batch request → server-streamed ACKs)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFiles(self, request, context):
        """Step 2-B: download N files (single batch request → server-streamed FileChunks)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileHistory(self, request, context):
        """Step 3: look up a file's backup version history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadHistoryVersion(self, request, context):
        """Step 4: download a specific version of a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreHistoryVersion(self, request, context):
        """Step 5: restore a server-side file to a specific version (overwrite)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=sync__pb2.Empty.FromString,
                    response_serializer=sync__pb2.Pong.SerializeToString,
            ),
            'Delta': grpc.unary_unary_rpc_method_handler(
                    servicer.Delta,
                    request_deserializer=sync__pb2.DeltaRequest.FromString,
                    response_serializer=sync__pb2.DeltaResponse.SerializeToString,
            ),
            'UploadFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=sync__pb2.UploadBatch.FromString,
                    response_serializer=sync__pb2.UploadAck.SerializeToString,
            ),
            'DownloadFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFiles,
                    request_deserializer=sync__pb2.DownloadBatchRequest.FromString,
                    response_serializer=sync__pb2.FileChunk.SerializeToString,
            ),
            'GetFileHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileHistory,
                    request_deserializer=sync__pb2.HistoryRequest.FromString,
                    response_serializer=sync__pb2.HistoryResponse.SerializeToString,
            ),
            'DownloadHistoryVersion': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadHistoryVersion,
                    request_deserializer=sync__pb2.HistoryVersionDownloadRequest.FromString,
                    response_serializer=sync__pb2.FileChunk.SerializeToString,
            ),
            'RestoreHistoryVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreHistoryVersion,
                    request_deserializer=sync__pb2.RestoreHistoryRequest.FromString,
                    response_serializer=sync__pb2.RestoreHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'obsidian.sync.v1.SyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('obsidian.sync.v1.SyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncService:
    """─── Service ──────────────────────────────────────────────────────────────────

    Bookmarks are included in regular file sync as .obsidian/bookmarks.json.
    No separate RPC is needed for them.

    For gRPC-Web compatibility, bidirectional streaming was dropped in favor of batch-request-based
    server streaming.

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obsidian.sync.v1.SyncService/Ping',
            sync__pb2.Empty.SerializeToString,
            sync__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obsidian.sync.v1.SyncService/Delta',
            sync__pb2.DeltaRequest.SerializeToString,
            sync__pb2.DeltaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/obsidian.sync.v1.SyncService/UploadFiles',
            sync__pb2.UploadBatch.SerializeToString,
            sync__pb2.UploadAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/obsidian.sync.v1.SyncService/DownloadFiles',
            sync__pb2.DownloadBatchRequest.SerializeToString,
            sync__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obsidian.sync.v1.SyncService/GetFileHistory',
            sync__pb2.HistoryRequest.SerializeToString,
            sync__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadHistoryVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/obsidian.sync.v1.SyncService/DownloadHistoryVersion',
            sync__pb2.HistoryVersionDownloadRequest.SerializeToString,
            sync__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreHistoryVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obsidian.sync.v1.SyncService/RestoreHistoryVersion',
            sync__pb2.RestoreHistoryRequest.SerializeToString,
            sync__pb2.RestoreHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
